version: '4'

services:
  mzhn-prereg-app:
    container_name: mzhn-prereg-app
    restart: always
    env_file:
      - .env
    environment:
      - PG_HOST=prereg-pg
    build:
      context: .
      args:
        - APP_PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - prereg-pg

  prereg-pg:
    image: postgres:14.13-alpine3.20
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - pg-prereg-data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432

volumes:
  pg-prereg-data:
  