"""add_assigned_to

Revision ID: 1e5a2d55d3f5
Revises: af48c6ed3e09
Create Date: 2024-10-19 22:21:20.685303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5a2d55d3f5'
down_revision: Union[str, None] = 'af48c6ed3e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preregs', sa.Column('assigned_to', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preregs', 'assigned_to')
    # ### end Alembic commands ###
